CREATE DATABASE CAR_RENTAL;

CREATE TABLE CAR_RENTAL.CUSTOMER(
SSNUMBER CHAR(9) NOT NULL,
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
DOB VARCHAR(12) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
PHONE VARCHAR(12) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
PRIMARY KEY (SSNUMBER));


CREATE TABLE CAR_RENTAL.EMPLOYEE(
SSNUMBER CHAR(9) NOT NULL,
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
DOB VARCHAR(12) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
PHONE VARCHAR(12) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
JOB_TITLE VARCHAR(20) NOT NULL,
PRIMARY KEY (SSNUMBER));


CREATE TABLE CAR_RENTAL.USERACCOUNT(
USERID CHAR(50) NOT NULL,
USERNAME VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(30) NOT NULL, 
EMAIL VARCHAR(30) NOT NULL, 
PRIMARY KEY (USERNAME));